# Generated by Django 3.1 on 2020-08-11 19:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('data_criado', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('qtd_ml', models.PositiveIntegerField()),
                ('concentracao_cbd_mg', models.PositiveIntegerField()),
                ('tipo_garrafa', models.CharField(choices=[('PPT', 'Pipeta'), ('SPR', 'Spray')], default='PPT', max_length=3)),
                ('preco', models.FloatField()),
                ('data_criado', models.DateTimeField(default=django.utils.timezone.now)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calc.fabricante')),
            ],
        ),
    ]
