# Generated by Django 3.1 on 2020-08-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fabricante',
            new_name='Marca',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='fabricante',
            new_name='marca',
        ),
    ]
